### ISSUE TITLE
Compile error on Unity 2022.3.0f1

### ISSUE THREAD

**Issue by KichangKim** [Unity-Technologies/com.unity.search.extensions#42]
SerchView.cs:198
https://github.com/Unity-Technologies/com.unity.search.extensions/blob/12f447a7638af7a4a3b337df32f1343aad232b99/package/Overlays/SearchView.cs#L198
```csharp
#if UNITY_2022_2
        int ISearchView.cursorIndex => 0;
#endif
```
Should be change to 
```csharp
#if UNITY_2022_2_OR_NEWER
        int ISearchView.cursorIndex => 0;
#endif
```

**Comment by didier-pikpok** [comment]
note that this also trigger errors on the newly released 2022.3.0f1 LTS, as it is also not caught by the 
```
#if UNITY_2022_2
        int ISearchView.cursorIndex => 0;
#endif
```

**Comment by KichangKim** [comment]
> note that this also trigger errors on the newly released 2022.3.0f1 LTS, as it is also not caught by the
> 
> ```
> #if UNITY_2022_2
>         int ISearchView.cursorIndex => 0;
> #endif
> ```

I mistyped Unity version. As your comment,  2022.3.0f1 makes error. (2023.1.0f1 is not released yet :) )

**Comment by KichangKim** [comment]
For both 2022.3 and 2023.1, the fix should be this?
```csharp
#if UNITY_2022_2 || UNITY_2022_3
        int ISearchView.cursorIndex => 0;
#endif
```

**Comment by Shadorc** [comment]
Fixed by https://github.com/Unity-Technologies/com.unity.search.extensions/commit/a2009acdeb14dbdad9653a5c8758874ef0304a32 🎉
